# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import pathlib
import typing

__all__ = [
    "NONE_CONTENT_TYPE",
    "AddRequestsResponse",
    "DatasetItemsListPage",
    "DatasetMetadata",
    "FileSystemDatasetClient",
    "FileSystemKeyValueStoreClient",
    "FileSystemRequestQueueClient",
    "KeyValueStoreListKeysResult",
    "KeyValueStoreMetadata",
    "KeyValueStoreRecord",
    "KeyValueStoreRecordMetadata",
    "ProcessedRequest",
    "RequestQueueMetadata",
    "UnprocessedRequest",
]

class AddRequestsResponse(typing.TypedDict):
    processedRequests: builtins.list[ProcessedRequest]
    unprocessedRequests: builtins.list[UnprocessedRequest]

class DatasetItemsListPage(typing.TypedDict):
    count: builtins.int
    offset: builtins.int
    limit: builtins.int
    total: builtins.int
    desc: builtins.bool
    items: builtins.list[dict[builtins.str, typing.Any]]

class DatasetMetadata(typing.TypedDict):
    id: builtins.str
    name: builtins.str | None
    accessedAt: datetime.datetime
    createdAt: datetime.datetime
    modifiedAt: datetime.datetime
    itemCount: builtins.int

class KeyValueStoreListKeysResult(typing.TypedDict):
    items: builtins.list[KeyValueStoreRecordMetadata]
    count: builtins.int
    limit: builtins.int
    exclusiveStartKey: builtins.str | None
    isTruncated: builtins.bool
    nextExclusiveStartKey: builtins.str | None

class KeyValueStoreMetadata(typing.TypedDict):
    id: builtins.str
    name: builtins.str | None
    accessedAt: datetime.datetime
    createdAt: datetime.datetime
    modifiedAt: datetime.datetime

class KeyValueStoreRecord(typing.TypedDict):
    key: builtins.str
    contentType: builtins.str
    size: builtins.int
    value: builtins.bytes

class KeyValueStoreRecordMetadata(typing.TypedDict):
    key: builtins.str
    contentType: builtins.str
    size: builtins.int

class ProcessedRequest(typing.TypedDict):
    requestId: builtins.str
    uniqueKey: builtins.str
    wasAlreadyPresent: builtins.bool
    wasAlreadyHandled: builtins.bool

class RequestQueueMetadata(typing.TypedDict):
    id: builtins.str
    name: builtins.str | None
    accessedAt: datetime.datetime
    createdAt: datetime.datetime
    modifiedAt: datetime.datetime
    handledRequestCount: builtins.int
    pendingRequestCount: builtins.int
    totalRequestCount: builtins.int

class UnprocessedRequest(typing.TypedDict):
    uniqueKey: builtins.str
    url: builtins.str
    method: builtins.str | None

NONE_CONTENT_TYPE: builtins.str

@typing.final
class FileSystemDatasetClient:
    @property
    def path_to_dataset(self) -> pathlib.Path:
        r"""
        Path to the dataset directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: builtins.str | None = None,
        name: builtins.str | None = None,
        alias: builtins.str | None = None,
        storage_dir: builtins.str = "./storage",
        use_test_clock: builtins.bool = False,
    ) -> FileSystemDatasetClient: ...
    def advance_clock_for_testing(self, duration: datetime.timedelta) -> None:
        r"""
        Advance the client's clock by ``duration``. Only usable when the client
        was opened with ``use_test_clock=True``; raises ``ValueError`` otherwise.
        """
    async def get_metadata(self) -> DatasetMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def push_data(self, data: typing.Any) -> None: ...
    async def get_data(
        self,
        offset: builtins.int = 0,
        limit: builtins.int | None = None,
        desc: builtins.bool = False,
        skip_empty: builtins.bool = False,
    ) -> DatasetItemsListPage: ...

@typing.final
class FileSystemKeyValueStoreClient:
    @property
    def path_to_kvs(self) -> pathlib.Path:
        r"""
        Path to the key-value store directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: builtins.str | None = None,
        name: builtins.str | None = None,
        alias: builtins.str | None = None,
        storage_dir: builtins.str = "./storage",
        use_test_clock: builtins.bool = False,
        adopt: typing.Sequence[tuple[builtins.str, typing.Sequence[tuple[builtins.str, builtins.str]]]] = [],
    ) -> FileSystemKeyValueStoreClient:
        r"""
        Open an existing key-value store or create a new one.

        ``adopt`` declares keys whose value file may already be on disk without
        a metadata sidecar — written into the store directory out-of-band by a
        CLI, say — so no key currently addresses it. Each entry
        is a ``(key, [(filename, content_type), ...])`` pair: open writes the
        missing sidecar, binding the key to whichever declared file it finds, so
        the file becomes an ordinary record (readable via ``get_value``, visible
        in ``list_keys``). Value bytes are never touched. A key that already has
        a usable record is left alone; declaring several files that all exist
        raises ``ValueError``, since there is no way to guess which one the key
        means. The canonical case is a run's input (``INPUT``, ``INPUT.json``,
        ...), but nothing here is specific to it.
        """
    def advance_clock_for_testing(self, duration: datetime.timedelta) -> None:
        r"""
        Advance the client's clock by ``duration``. Only usable when the client
        was opened with ``use_test_clock=True``; raises ``ValueError`` otherwise.
        """
    async def get_metadata(self) -> KeyValueStoreMetadata: ...
    async def drop_storage(self) -> None: ...
    async def get_value(self, key: builtins.str) -> KeyValueStoreRecord | None:
        r"""
        Get a tracked record (value file + metadata sidecar) by key.

        A value file with no sidecar is not a record: declare it in ``adopt``
        when opening the store and it becomes one.
        """
    async def resolve_value(
        self, key: builtins.str, bare_fallbacks: typing.Sequence[tuple[builtins.str, builtins.str]]
    ) -> KeyValueStoreRecord | None:
        r"""
        Resolve a key to a record, transparently falling back to out-of-band
        ("bare") value files that have no metadata sidecar.

        Tries the tracked record for the literal `key` first (its content type
        comes verbatim from the sidecar), then probes each `(extension,
        content_type)` in `bare_fallbacks` as a bare `key + extension` file,
        reporting the declared content type on a match. The first match wins;
        the returned record is always keyed by the requested `key`. Returns
        `None` if nothing resolves.

        The core does no MIME inference of its own — the caller declares which
        extensions map to which content type. An empty ``content_type`` keeps
        the matched file's synthesized ``application/octet-stream``.

        .. deprecated::
           Declare the file in ``open``'s ``adopt`` instead: adoption turns it
           into a real record once, so ``get_value`` and ``list_keys`` both see
           it, rather than every reader re-declaring the same probe list for a
           file that stays invisible to listings.
        """
    async def resolve_existing_key(
        self, key: builtins.str, bare_fallbacks: typing.Sequence[builtins.str]
    ) -> builtins.str | None:
        r"""
        Resolve a key to the on-disk key that actually exists, using the same
        fallback probe order as `resolve_value` but without reading the value.
        Returns the matched key (the literal key or `key + extension`), or
        `None` if nothing exists. Pass the result to `get_public_url` so the URL
        points at the file that exists.

        .. deprecated::
           Declare the file in ``open``'s ``adopt`` instead, then pass ``key``
           straight to ``get_public_url``.
        """
    async def set_value(
        self,
        key: builtins.str,
        value: builtins.bytes,
        content_type: builtins.str | None = None,
        filename: builtins.str | None = None,
    ) -> None:
        r"""
        Set a value from bytes.

        ``filename`` binds the key to that on-disk name instead of the key
        itself (``INPUT`` → ``input.json``), recorded in the sidecar so every
        read path finds it. It is used as-is — unlike the key, it is not
        percent-encoded — and must be a plain filename directly inside the
        store directory. Re-binding a key deletes the file it was bound to
        before.
        """
    async def purge(self, keep: typing.Sequence[builtins.str] = []) -> None:
        r"""
        Delete all records except those whose keys are listed in `keep`.

        Matching is by exact key (no extension globbing): to spare both `INPUT`
        and `INPUT.json`, pass both. The store metadata is always kept.
        """
    async def delete_value(self, key: builtins.str) -> None:
        r"""
        Delete a single value (and its metadata sidecar) by key.
        """
    async def list_keys(
        self,
        exclusive_start_key: builtins.str | None = None,
        limit: builtins.int | None = None,
        prefix: builtins.str | None = None,
        bare_fallbacks: typing.Sequence[tuple[builtins.str, builtins.str]] = [],
    ) -> KeyValueStoreListKeysResult:
        r"""
        List a single self-describing page of keys.

        Returns a `KeyValueStoreListKeysResult` dict matching crawlee's
        `KeyValueStoreListKeysResult` contract: the page's `items` bundled with
        the echoed `exclusiveStartKey`/`limit`, an `isTruncated` flag, and the
        derived `nextExclusiveStartKey` (the cursor for the next call, set iff
        `isTruncated`). Call it repeatedly, feeding `nextExclusiveStartKey` back
        as `exclusive_start_key`, to stream every key one page at a time.

        `limit` bounds the page size (defaults to 1000) and is echoed back on
        the result. A bare file (declared via `bare_fallbacks`) whose on-disk
        value-file name collides with a tracked record is dropped.

        `bare_fallbacks` additionally surfaces out-of-band ("bare") value files
        that have no metadata sidecar (e.g. a CLI-written `INPUT.json`) as regular
        keys. Each entry is a `(name, content_type)` tuple where `name` is the
        file's on-disk key: if that file exists with no tracked record, it is
        listed under `name` (an empty `content_type` reports the synthesized
        `application/octet-stream`). Pass an empty list (the default) to list only
        tracked records.

        .. deprecated::
           ``bare_fallbacks``: a surfaced bare key does NOT round-trip through
           the strict read path — ``get_value`` / ``record_exists`` only see
           tracked records, so it reads back as absent. Declare the file in
           ``open``'s ``adopt`` instead and it is both listed and readable as an
           ordinary record.
        """
    async def get_public_url(self, key: builtins.str) -> builtins.str:
        r"""
        Build a `file://` URL for `key`'s value file. Honors a sidecar's bound
        `filename`, but does not stat the file, so the URL is returned whether
        or not anything is there yet. Bare-file extensions are not probed — a
        sidecar-less file is addressable once it has been adopted on ``open``.
        """
    async def record_exists(self, key: builtins.str) -> builtins.bool:
        r"""
        Check whether a tracked record (value file + metadata sidecar) exists for
        `key`. A sidecar whose bound value file is missing is not a record, and
        neither is a value file with no sidecar until it is adopted on ``open``.
        """

@typing.final
class FileSystemRequestQueueClient:
    @property
    def path_to_rq(self) -> pathlib.Path:
        r"""
        Path to the request queue directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: builtins.str | None = None,
        name: builtins.str | None = None,
        alias: builtins.str | None = None,
        storage_dir: builtins.str = "./storage",
        use_test_clock: builtins.bool = False,
        request_queue_access: typing.Literal["single", "shared"] = "single",
    ) -> FileSystemRequestQueueClient:
        r"""
        Open a request queue.

        ``use_test_clock``: see ``advance_clock_for_testing`` below.

        ``request_queue_access`` (default ``"single"``): how the on-disk queue
        is expected to be accessed. With ``"single"`` (the default, tuned for
        the common single-process crawl), the caller asserts nothing else is
        using this queue and any in-progress locks are reclaimed immediately,
        so a request whose previous run died is instantly re-fetchable. Use
        ``"shared"`` when multiple processes share the same on-disk queue
        concurrently: any future-dated ``orderNo`` is then respected as a
        potential live peer's lock, and crashed peers' locks expire naturally
        on the wall clock — otherwise you risk two peers processing the same
        request.
        """
    def advance_clock_for_testing(self, duration: datetime.timedelta) -> None:
        r"""
        Advance the client's clock by ``duration``. Only usable when the client
        was opened with ``use_test_clock=True``; raises ``ValueError`` otherwise.

        This is the hook that lets Python tests using ``freezegun`` or
        similar frameworks exercise lock-expiry behavior — frozen Python
        clocks don't reach into native code, so the test must drive the
        Rust-side clock explicitly via this method.
        """
    async def get_metadata(self) -> RequestQueueMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def add_batch_of_requests(self, requests: list, forefront: builtins.bool = False) -> AddRequestsResponse: ...
    async def get_request(self, unique_key: builtins.str) -> dict[str, typing.Any] | None: ...
    async def fetch_next_request(self) -> dict[str, typing.Any] | None: ...
    async def mark_request_as_handled(self, request: typing.Any) -> ProcessedRequest | None: ...
    async def reclaim_request(
        self, request: typing.Any, forefront: builtins.bool = False
    ) -> ProcessedRequest | None: ...
    async def is_empty(self) -> builtins.bool: ...
    async def is_finished(self) -> builtins.bool: ...
    async def set_expected_request_processing_time(self, duration: datetime.timedelta) -> None: ...
    async def persist_state(self) -> None: ...
