# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import pathlib
import typing

__all__ = [
    "DatasetItemIterator",
    "FileSystemDatasetClient",
    "FileSystemKeyValueStoreClient",
    "FileSystemRequestQueueClient",
    "KvsKeyIterator",
    "AddRequestsResponse",
    "DatasetItemsListPage",
    "DatasetMetadata",
    "KeyValueStoreMetadata",
    "KeyValueStoreRecord",
    "KeyValueStoreRecordMetadata",
    "ProcessedRequest",
    "RequestQueueMetadata",
    "UnprocessedRequest",
]

class DatasetMetadata(typing.TypedDict):
    id: builtins.str
    name: builtins.str | None
    accessedAt: datetime.datetime
    createdAt: datetime.datetime
    modifiedAt: datetime.datetime
    itemCount: builtins.int

class KeyValueStoreMetadata(typing.TypedDict):
    id: builtins.str
    name: builtins.str | None
    accessedAt: datetime.datetime
    createdAt: datetime.datetime
    modifiedAt: datetime.datetime

class KeyValueStoreRecordMetadata(typing.TypedDict):
    key: builtins.str
    contentType: builtins.str
    size: builtins.int

class KeyValueStoreRecord(typing.TypedDict):
    key: builtins.str
    contentType: builtins.str
    size: builtins.int
    value: builtins.bytes

class RequestQueueMetadata(typing.TypedDict):
    id: builtins.str
    name: builtins.str | None
    accessedAt: datetime.datetime
    createdAt: datetime.datetime
    modifiedAt: datetime.datetime
    hadMultipleClients: builtins.bool
    handledRequestCount: builtins.int
    pendingRequestCount: builtins.int
    totalRequestCount: builtins.int

class DatasetItemsListPage(typing.TypedDict):
    count: builtins.int
    offset: builtins.int
    limit: builtins.int
    total: builtins.int
    desc: builtins.bool
    items: builtins.list[dict[builtins.str, typing.Any]]

class ProcessedRequest(typing.TypedDict):
    requestId: builtins.str
    uniqueKey: builtins.str
    wasAlreadyPresent: builtins.bool
    wasAlreadyHandled: builtins.bool

class UnprocessedRequest(typing.TypedDict):
    uniqueKey: builtins.str
    url: builtins.str
    method: builtins.str | None

class AddRequestsResponse(typing.TypedDict):
    processedRequests: builtins.list[ProcessedRequest]
    unprocessedRequests: builtins.list[UnprocessedRequest]

@typing.final
class DatasetItemIterator:
    def __aiter__(self) -> DatasetItemIterator: ...
    async def __anext__(self) -> dict[str, typing.Any]: ...

@typing.final
class FileSystemDatasetClient:
    @property
    def path_to_dataset(self) -> pathlib.Path:
        r"""
        Path to the dataset directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: builtins.str | None = None,
        name: builtins.str | None = None,
        alias: builtins.str | None = None,
        storage_dir: builtins.str = "./storage",
        use_test_clock: builtins.bool = False,
    ) -> FileSystemDatasetClient: ...
    def advance_clock_for_testing(self, duration: datetime.timedelta) -> None:
        r"""
        Advance the client's clock by ``duration``. Only usable when the client
        was opened with ``use_test_clock=True``; raises ``ValueError`` otherwise.
        """
    async def get_metadata(self) -> DatasetMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def push_data(self, data: typing.Any) -> None: ...
    async def get_data(
        self,
        offset: builtins.int = 0,
        limit: builtins.int | None = None,
        desc: builtins.bool = False,
        skip_empty: builtins.bool = False,
    ) -> DatasetItemsListPage: ...
    def iterate_items(
        self,
        offset: builtins.int = 0,
        limit: builtins.int | None = None,
        desc: builtins.bool = False,
        skip_empty: builtins.bool = False,
        page_size: builtins.int | None = None,
    ) -> DatasetItemIterator: ...

@typing.final
class FileSystemKeyValueStoreClient:
    @property
    def path_to_kvs(self) -> pathlib.Path:
        r"""
        Path to the key-value store directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: builtins.str | None = None,
        name: builtins.str | None = None,
        alias: builtins.str | None = None,
        storage_dir: builtins.str = "./storage",
        use_test_clock: builtins.bool = False,
    ) -> FileSystemKeyValueStoreClient: ...
    def advance_clock_for_testing(self, duration: datetime.timedelta) -> None:
        r"""
        Advance the client's clock by ``duration``. Only usable when the client
        was opened with ``use_test_clock=True``; raises ``ValueError`` otherwise.
        """
    async def get_metadata(self) -> KeyValueStoreMetadata: ...
    async def drop_storage(self) -> None: ...
    async def get_value(self, key: builtins.str) -> KeyValueStoreRecord | None: ...
    async def set_value(
        self, key: builtins.str, value: builtins.bytes, content_type: builtins.str | None = None
    ) -> None: ...
    async def purge(self, keep: typing.Sequence[builtins.str] = []) -> None:
        r"""
        Delete all records except those whose keys are listed in `keep`.

        Matching is by exact key (no extension globbing): to spare both `INPUT`
        and `INPUT.json`, pass both. The store metadata is always kept.
        """
    def iterate_keys(
        self,
        exclusive_start_key: builtins.str | None = None,
        limit: builtins.int | None = None,
        page_size: builtins.int | None = None,
        prefix: builtins.str | None = None,
    ) -> KvsKeyIterator: ...
    async def get_public_url(self, key: builtins.str) -> builtins.str: ...
    async def record_exists(self, key: builtins.str) -> builtins.bool: ...

@typing.final
class FileSystemRequestQueueClient:
    @property
    def path_to_rq(self) -> pathlib.Path:
        r"""
        Path to the request queue directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: builtins.str | None = None,
        name: builtins.str | None = None,
        alias: builtins.str | None = None,
        storage_dir: builtins.str = "./storage",
        use_test_clock: builtins.bool = False,
        assume_sole_owner: builtins.bool = True,
    ) -> FileSystemRequestQueueClient:
        r"""
        Open a request queue.

        ``use_test_clock``: see ``advance_clock_for_testing`` below.

        ``assume_sole_owner`` (default ``True``): controls how locks on disk
        are treated at open time. With ``True`` (the default, tuned for the
        common single-process crawl), the caller asserts nothing else is using
        this queue and any in-progress locks are reclaimed immediately, so a
        request whose previous run died is instantly re-fetchable. Set to
        ``False`` when multiple processes share the same on-disk queue
        concurrently: any future-dated ``orderNo`` is then respected as a
        potential live peer's lock, and crashed peers' locks expire naturally
        on the wall clock — otherwise you risk two peers processing the same
        request.
        """
    def advance_clock_for_testing(self, duration: datetime.timedelta) -> None:
        r"""
        Advance the client's clock by ``duration``. Only usable when the client
        was opened with ``use_test_clock=True``; raises ``ValueError`` otherwise.

        This is the hook that lets Python tests using ``freezegun`` or
        similar frameworks exercise lock-expiry behavior — frozen Python
        clocks don't reach into native code, so the test must drive the
        Rust-side clock explicitly via this method.
        """
    async def get_metadata(self) -> RequestQueueMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def add_batch_of_requests(self, requests: list, forefront: builtins.bool = False) -> AddRequestsResponse: ...
    async def get_request(self, unique_key: builtins.str) -> dict[str, typing.Any] | None: ...
    async def fetch_next_request(self) -> dict[str, typing.Any] | None: ...
    async def mark_request_as_handled(self, request: typing.Any) -> ProcessedRequest | None: ...
    async def reclaim_request(
        self, request: typing.Any, forefront: builtins.bool = False
    ) -> ProcessedRequest | None: ...
    async def is_empty(self) -> builtins.bool: ...
    async def is_finished(self) -> builtins.bool: ...
    async def set_expected_request_processing_time(self, duration: datetime.timedelta) -> None: ...
    async def persist_state(self) -> None: ...

@typing.final
class KvsKeyIterator:
    def __aiter__(self) -> KvsKeyIterator: ...
    async def __anext__(self) -> KeyValueStoreRecordMetadata: ...
