# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import pathlib
import typing

__all__ = [
    "DatasetItemIterator",
    "FileSystemDatasetClient",
    "FileSystemKeyValueStoreClient",
    "FileSystemRequestQueueClient",
    "KvsKeyIterator",
    "AddRequestsResponse",
    "DatasetItemsListPage",
    "DatasetMetadata",
    "KeyValueStoreMetadata",
    "KeyValueStoreRecord",
    "KeyValueStoreRecordMetadata",
    "ProcessedRequest",
    "RequestQueueMetadata",
    "UnprocessedRequest",
]

class DatasetMetadata(typing.TypedDict):
    id: builtins.str
    name: typing.Optional[builtins.str]
    accessedAt: builtins.str
    createdAt: builtins.str
    modifiedAt: builtins.str
    itemCount: builtins.int

class KeyValueStoreMetadata(typing.TypedDict):
    id: builtins.str
    name: typing.Optional[builtins.str]
    accessedAt: builtins.str
    createdAt: builtins.str
    modifiedAt: builtins.str

class KeyValueStoreRecordMetadata(typing.TypedDict):
    key: builtins.str
    contentType: builtins.str
    size: typing.Optional[builtins.int]

class KeyValueStoreRecord(typing.TypedDict):
    key: builtins.str
    contentType: builtins.str
    size: typing.Optional[builtins.int]
    value: builtins.bytes

class RequestQueueMetadata(typing.TypedDict):
    id: builtins.str
    name: typing.Optional[builtins.str]
    accessedAt: builtins.str
    createdAt: builtins.str
    modifiedAt: builtins.str
    hadMultipleClients: builtins.bool
    handledRequestCount: builtins.int
    pendingRequestCount: builtins.int
    totalRequestCount: builtins.int

class DatasetItemsListPage(typing.TypedDict):
    count: builtins.int
    offset: builtins.int
    limit: builtins.int
    total: builtins.int
    desc: builtins.bool
    items: builtins.list[dict[builtins.str, typing.Any]]

class ProcessedRequest(typing.TypedDict):
    id: typing.Optional[builtins.str]
    uniqueKey: builtins.str
    wasAlreadyPresent: builtins.bool
    wasAlreadyHandled: builtins.bool

class UnprocessedRequest(typing.TypedDict):
    uniqueKey: builtins.str
    url: builtins.str
    method: typing.Optional[builtins.str]

class AddRequestsResponse(typing.TypedDict):
    processedRequests: builtins.list[ProcessedRequest]
    unprocessedRequests: builtins.list[UnprocessedRequest]

@typing.final
class DatasetItemIterator:
    def __aiter__(self) -> DatasetItemIterator: ...
    async def __anext__(self) -> dict[str, typing.Any]: ...

@typing.final
class FileSystemDatasetClient:
    @property
    def path_to_dataset(self) -> pathlib.Path:
        r"""
        Path to the dataset directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: typing.Optional[builtins.str] = None,
        name: typing.Optional[builtins.str] = None,
        alias: typing.Optional[builtins.str] = None,
        storage_dir: builtins.str = "./storage",
    ) -> FileSystemDatasetClient: ...
    async def get_metadata(self) -> DatasetMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def push_data(self, data: typing.Any) -> None: ...
    async def get_data(
        self,
        offset: builtins.int = 0,
        limit: builtins.int = 999999999999,
        desc: builtins.bool = False,
        skip_empty: builtins.bool = False,
    ) -> DatasetItemsListPage: ...
    def iterate_items(
        self,
        offset: builtins.int = 0,
        limit: typing.Optional[builtins.int] = None,
        desc: builtins.bool = False,
        skip_empty: builtins.bool = False,
        page_size: typing.Optional[builtins.int] = None,
    ) -> DatasetItemIterator: ...

@typing.final
class FileSystemKeyValueStoreClient:
    @property
    def path_to_kvs(self) -> pathlib.Path:
        r"""
        Path to the key-value store directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: typing.Optional[builtins.str] = None,
        name: typing.Optional[builtins.str] = None,
        alias: typing.Optional[builtins.str] = None,
        storage_dir: builtins.str = "./storage",
    ) -> FileSystemKeyValueStoreClient: ...
    async def get_metadata(self) -> KeyValueStoreMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def get_value(self, key: builtins.str) -> typing.Optional[KeyValueStoreRecord]: ...
    async def set_value(
        self, key: builtins.str, value: builtins.bytes, content_type: typing.Optional[builtins.str] = None
    ) -> None: ...
    async def delete_value(self, key: builtins.str) -> None: ...
    def iterate_keys(
        self,
        exclusive_start_key: typing.Optional[builtins.str] = None,
        limit: typing.Optional[builtins.int] = None,
        page_size: typing.Optional[builtins.int] = None,
    ) -> KvsKeyIterator: ...
    async def get_public_url(self, key: builtins.str) -> builtins.str: ...
    async def record_exists(self, key: builtins.str) -> builtins.bool: ...

@typing.final
class FileSystemRequestQueueClient:
    @property
    def path_to_rq(self) -> pathlib.Path:
        r"""
        Path to the request queue directory.
        """
    @property
    def path_to_metadata(self) -> pathlib.Path:
        r"""
        Path to the metadata file.
        """
    @staticmethod
    async def open(
        id: typing.Optional[builtins.str] = None,
        name: typing.Optional[builtins.str] = None,
        alias: typing.Optional[builtins.str] = None,
        storage_dir: builtins.str = "./storage",
    ) -> FileSystemRequestQueueClient: ...
    async def get_metadata(self) -> RequestQueueMetadata: ...
    async def drop_storage(self) -> None: ...
    async def purge(self) -> None: ...
    async def add_batch_of_requests(self, requests: list, forefront: builtins.bool = False) -> AddRequestsResponse: ...
    async def get_request(self, unique_key: builtins.str) -> typing.Optional[dict[str, typing.Any]]: ...
    async def fetch_next_request(self) -> typing.Optional[dict[str, typing.Any]]: ...
    async def mark_request_as_handled(self, request: typing.Any) -> typing.Optional[ProcessedRequest]: ...
    async def reclaim_request(
        self, request: typing.Any, forefront: builtins.bool = False
    ) -> typing.Optional[ProcessedRequest]: ...
    async def is_empty(self) -> builtins.bool: ...
    async def persist_state(self) -> None: ...

@typing.final
class KvsKeyIterator:
    def __aiter__(self) -> KvsKeyIterator: ...
    async def __anext__(self) -> KeyValueStoreRecordMetadata: ...
