// Metadata interfaces (DatasetMetadata, KeyValueStoreMetadata,
// RequestQueueMetadata) and the KeyValueStoreRecord interface are
// auto-generated by napi-rs from `#[napi(object)]` structs in src/models.rs —
// the metadata datetime fields come through as native `Date` (thanks to napi's
// `chrono_date` feature) and the record's `value` comes through as a `Buffer`.

export interface DatasetItemsListPage {
    count: number;
    offset: number;
    limit: number;
    total: number;
    desc: boolean;
    items: Record<string, unknown>[];
}

export interface KeyValueStoreStreamRecord {
    key: string;
    contentType: string;
    size: number;
    stream: ReadableStream<Uint8Array>;
}

export interface KeyValueStoreRecordMetadata {
    key: string;
    contentType: string;
    size: number;
}

export interface ProcessedRequest {
    requestId: string;
    uniqueKey: string;
    wasAlreadyPresent: boolean;
    wasAlreadyHandled: boolean;
}

export interface UnprocessedRequest {
    uniqueKey: string;
    url: string;
    method?: string;
}

export interface AddRequestsResponse {
    processedRequests: ProcessedRequest[];
    unprocessedRequests: UnprocessedRequest[];
}

// The following `interface` declarations merge with the napi-generated `declare class`es
// further down in this file, adding the JS-side wrappers defined in `lib.js` directly onto
// the class signatures.

export interface DatasetItemIterator {
    [Symbol.asyncIterator](): AsyncIterator<Record<string, unknown>>;
}

export interface KvsKeyIterator {
    [Symbol.asyncIterator](): AsyncIterator<KeyValueStoreRecordMetadata>;
}

export interface FileSystemKeyValueStoreClient {
    /**
     * Get a value as a ReadableStream of bytes. Returns null if the key doesn't exist.
     *
     * When `requireRecordMetadata` is `false`, a value file without a metadata
     * sidecar is also streamable (used to read out-of-band files such as a
     * CLI-written `INPUT.json`). Defaults to `true` (sidecar required).
     */
    getValueStream(
        key: string,
        requireRecordMetadata?: boolean,
    ): Promise<KeyValueStoreStreamRecord | null>;
    /** Set a value from a ReadableStream. Consumes the entire stream and writes atomically. */
    setValueStream(
        key: string,
        stream: ReadableStream<Uint8Array>,
        contentType?: string | null,
    ): Promise<void>;
}
