// Metadata interfaces (DatasetMetadata, KeyValueStoreMetadata,
// RequestQueueMetadata) are auto-generated by napi-rs from `#[napi(object)]`
// structs in src/models.rs — their datetime fields come through as native
// `Date` thanks to napi's `chrono_date` feature.

export interface DatasetItemsListPage {
    count: number;
    offset: number;
    limit: number;
    total: number;
    desc: boolean;
    items: Record<string, unknown>[];
}

export interface KeyValueStoreRecord {
    key: string;
    contentType: string;
    size: number | null;
    value: Buffer;
}

export interface KeyValueStoreStreamRecord {
    key: string;
    contentType: string;
    size: number | null;
    stream: ReadableStream<Uint8Array>;
}

export interface KeyValueStoreRecordMetadata {
    key: string;
    contentType: string;
    size: number | null;
}

export interface ProcessedRequest {
    requestId: string;
    uniqueKey: string;
    wasAlreadyPresent: boolean;
    wasAlreadyHandled: boolean;
}

export interface UnprocessedRequest {
    uniqueKey: string;
    url: string;
    method?: string | null;
}

export interface AddRequestsResponse {
    processedRequests: ProcessedRequest[];
    unprocessedRequests: UnprocessedRequest[];
}

// The following `interface` declarations merge with the napi-generated `declare class`es
// further down in this file, adding the JS-side wrappers defined in `lib.js` directly onto
// the class signatures.

export interface DatasetItemIterator {
    [Symbol.asyncIterator](): AsyncIterator<Record<string, unknown>>;
}

export interface KvsKeyIterator {
    [Symbol.asyncIterator](): AsyncIterator<KeyValueStoreRecordMetadata>;
}

export interface FileSystemKeyValueStoreClient {
    /** Get a value as a ReadableStream of bytes. Returns null if the key doesn't exist. */
    getValueStream(key: string): Promise<KeyValueStoreStreamRecord | null>;
    /** Set a value from a ReadableStream. Consumes the entire stream and writes atomically. */
    setValueStream(
        key: string,
        stream: ReadableStream<Uint8Array>,
        contentType?: string | null,
    ): Promise<void>;
}
