/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class FileSystemDatasetClient {
    static open(
        id?: string | undefined | null,
        name?: string | undefined | null,
        alias?: string | undefined | null,
        storageDir?: string | undefined | null,
        useTestClock?: boolean | undefined | null,
    ): Promise<FileSystemDatasetClient>;
    /**
     * Advance the client's clock by `millis` milliseconds. Only usable when
     * the client was opened with `useTestClock: true`; throws otherwise.
     */
    advanceClockForTesting(millis: number): void;
    get pathToDataset(): string;
    get pathToMetadata(): string;
    getMetadata(): Promise<DatasetMetadata>;
    dropStorage(): Promise<void>;
    purge(): Promise<void>;
    pushData(data: Record<string, unknown> | Record<string, unknown>[]): Promise<void>;
    getData(
        offset?: number | undefined | null,
        limit?: number | undefined | null,
        desc?: boolean | undefined | null,
        skipEmpty?: boolean | undefined | null,
    ): Promise<DatasetItemsListPage>;
}

export declare class FileSystemKeyValueStoreClient {
    /**
     * Open an existing key-value store or create a new one.
     *
     * `adopt` declares keys whose value file may already be on disk without a
     * metadata sidecar — written into the store directory out-of-band by a
     * CLI, say — so no key currently addresses it. For each
     * candidate, open writes the missing sidecar (binding the key to whichever
     * declared file it finds), so the file becomes an ordinary record:
     * readable via `getValue`, visible in `listKeys`. Value bytes are never
     * touched. A key that already has a usable record is left alone;
     * declaring several files that all exist throws, since there is no way to
     * guess which one the key means. The canonical case is a run's input
     * (`INPUT`, `INPUT.json`, ...), but nothing here is specific to it.
     */
    static open(
        id?: string | undefined | null,
        name?: string | undefined | null,
        alias?: string | undefined | null,
        storageDir?: string | undefined | null,
        useTestClock?: boolean | undefined | null,
        adopt?: Array<AdoptionCandidate> | undefined | null,
    ): Promise<FileSystemKeyValueStoreClient>;
    /**
     * Advance the client's clock by `millis` milliseconds. Only usable when
     * the client was opened with `useTestClock: true`; throws otherwise.
     */
    advanceClockForTesting(millis: number): void;
    get pathToKvs(): string;
    get pathToMetadata(): string;
    getMetadata(): Promise<KeyValueStoreMetadata>;
    dropStorage(): Promise<void>;
    /**
     * Delete all records except those whose keys are listed in `keep`.
     *
     * Matching is by exact key (no extension globbing): to spare both `INPUT`
     * and `INPUT.json`, pass both. The store metadata is always kept.
     */
    purge(keep?: Array<string> | undefined | null): Promise<void>;
    /**
     * Get a tracked record (value file + metadata sidecar) by key. Returns the
     * raw value bytes as a Buffer, or `undefined` if there is no such tracked record.
     *
     * A value file with no sidecar is not a record: declare it as an
     * `AdoptionCandidate` on `open` and it becomes one.
     */
    getValue(key: string): Promise<KeyValueStoreRecord | undefined>;
    /**
     * Resolve a key to a record, transparently falling back to out-of-band
     * ("bare") value files that have no metadata sidecar.
     *
     * Tries the tracked record for the literal `key` first (its content type
     * comes verbatim from the sidecar), then probes each `bareFallbacks` entry
     * as a bare `key + extension` file, reporting the declared content type on
     * a match. The first match wins; the returned record is always keyed by
     * the requested `key`. Returns `undefined` if nothing resolves.
     *
     * @deprecated Declare the file as an `AdoptionCandidate` on `open`
     * instead: adoption turns it into a real record once, so `getValue` and
     * `listKeys` both see it, rather than every reader re-declaring the same
     * probe list for a file that stays invisible to listings.
     */
    resolveValue(
        key: string,
        bareFallbacks: Array<BareFallback>,
    ): Promise<KeyValueStoreRecord | undefined>;
    /**
     * Resolve a key to the on-disk key that actually exists, using the same
     * fallback probe order as `resolveValue` but without reading the value.
     * Returns the matched key (the literal key or `key + extension`), or
     * `undefined` if nothing exists. Pass the result to `getPublicUrl` so the URL
     * points at the file that exists.
     *
     * @deprecated Declare the file as an `AdoptionCandidate` on `open`
     * instead, then pass `key` straight to `getPublicUrl`.
     */
    resolveExistingKey(key: string, bareFallbacks: Array<string>): Promise<string | undefined>;
    /**
     * Set a value from a Buffer.
     *
     * `filename` binds the key to that on-disk name instead of the key itself
     * (`INPUT` → `input.json`), recorded in the sidecar so every read path
     * finds it. It is used as-is — unlike the key, it is not percent-encoded —
     * and must be a plain filename directly inside the store directory.
     * Re-binding a key deletes the file it was bound to before.
     */
    setValue(
        key: string,
        value: Buffer,
        contentType?: string | undefined | null,
        filename?: string | undefined | null,
    ): Promise<void>;
    deleteValue(key: string): Promise<void>;
    /**
     * List a single self-describing page of keys.
     *
     * Returns a `KeyValueStoreListKeysResult` matching crawlee's
     * `KeyValueStoreListKeysResult` contract: the page's `items` bundled with
     * the echoed `exclusiveStartKey`/`limit`, an `isTruncated` flag, and the
     * derived `nextExclusiveStartKey` (the cursor for the next call, set iff
     * `isTruncated`). Call it repeatedly, feeding `nextExclusiveStartKey` back
     * as `exclusiveStartKey`, to stream every key one page at a time.
     *
     * `limit` bounds the page size (defaults to 1000) and is echoed back on
     * the result. A bare file (declared via `bareFallbacks`) whose on-disk
     * value-file name collides with a tracked record is dropped.
     *
     * `bareFallbacks` additionally surfaces out-of-band ("bare") value files
     * that have no metadata sidecar (e.g. a CLI-written `INPUT.json`) as regular
     * keys. Each entry is `{ name, contentType }` where `name` is the file's
     * on-disk key: if that file exists with no tracked record, it is listed
     * under `name`. Pass an empty array (the default) to list only tracked
     * records.
     *
     * `bareFallbacks` is deprecated: a surfaced bare key does NOT round-trip
     * through the strict read path — `getValue` / `recordExists` only see
     * tracked records, so it reads back as absent. Adopt the file on `open`
     * instead and it is both listed and readable as an ordinary record.
     */
    listKeys(
        exclusiveStartKey?: string | undefined | null,
        limit?: number | undefined | null,
        prefix?: string | undefined | null,
        bareFallbacks?: Array<ListBareFallback> | undefined | null,
    ): Promise<KeyValueStoreListKeysResult>;
    /**
     * Build a `file://` URL for `key`'s value file. Honors a sidecar's bound
     * `filename`, but does not stat the file, so the URL is returned whether
     * or not anything is there yet. Bare-file extensions are not probed — a
     * sidecar-less file is addressable once it has been adopted on `open`.
     */
    getPublicUrl(key: string): Promise<string>;
    /**
     * Check whether a tracked record (value file + metadata sidecar) exists for
     * `key`. A sidecar whose bound value file is missing is not a record, and
     * neither is a value file with no sidecar until it is adopted on `open`.
     */
    recordExists(key: string): Promise<boolean>;
}

export declare class FileSystemRequestQueueClient {
    /**
     * Open a request queue.
     *
     * `useTestClock`: see `advanceClockForTesting` below.
     *
     * `requestQueueAccess` (default `'single'`): how the on-disk queue is
     * expected to be accessed. With `'single'` (the default, tuned for the
     * common single-process crawl), the caller asserts nothing else is using
     * this queue and any in-progress locks are reclaimed immediately, so a
     * request whose previous run died is instantly re-fetchable. Use
     * `'shared'` when multiple processes share the same on-disk queue
     * concurrently: any future-dated `orderNo` is then respected as a
     * potential live peer's lock, and crashed peers' locks expire naturally
     * on the wall clock — otherwise you risk two peers processing the same
     * request.
     */
    static open(
        id?: string | undefined | null,
        name?: string | undefined | null,
        alias?: string | undefined | null,
        storageDir?: string | undefined | null,
        useTestClock?: boolean | undefined | null,
        requestQueueAccess?: 'single' | 'shared' | undefined | null,
    ): Promise<FileSystemRequestQueueClient>;
    /**
     * Advance the client's clock by `millis` milliseconds. Only usable when
     * the client was opened with `useTestClock: true`; throws otherwise.
     *
     * This is the hook that lets JS tests using `vi.useFakeTimers()` exercise
     * lock-expiry behavior — fake JS timers don't reach into native code, so
     * the test must drive the Rust-side clock explicitly via this method.
     */
    advanceClockForTesting(millis: number): void;
    get pathToRq(): string;
    get pathToMetadata(): string;
    getMetadata(): Promise<RequestQueueMetadata>;
    dropStorage(): Promise<void>;
    purge(): Promise<void>;
    addBatchOfRequests(
        requests: Record<string, unknown>[],
        forefront?: boolean | undefined | null,
    ): Promise<AddRequestsResponse>;
    getRequest(uniqueKey: string): Promise<Record<string, unknown> | undefined>;
    fetchNextRequest(): Promise<Record<string, unknown> | undefined>;
    markRequestAsHandled(request: Record<string, unknown>): Promise<ProcessedRequest | undefined>;
    reclaimRequest(
        request: Record<string, unknown>,
        forefront?: boolean | undefined | null,
    ): Promise<ProcessedRequest | undefined>;
    isEmpty(): Promise<boolean>;
    isFinished(): Promise<boolean>;
    setExpectedRequestProcessingTime(secs: number): Promise<void>;
    persistState(): Promise<void>;
}

/** Response from `addBatchOfRequests`. Mirrors the core's `AddRequestsResponse`. */
export interface AddRequestsResponse {
    processedRequests: Array<ProcessedRequest>;
    unprocessedRequests: Array<UnprocessedRequest>;
}

/**
 * One on-disk file an `AdoptionCandidate` may bind its key to. `filename` is
 * used verbatim (never percent-encoded) and must be a plain filename directly
 * inside the store directory; `contentType` is what the written sidecar will
 * report, since the core infers nothing from the extension.
 */
export interface AdoptableFile {
    filename: string;
    contentType: string;
}

/**
 * A key whose value file may already be on disk without a sidecar, plus the
 * files the caller is willing to adopt for it. See
 * `FileSystemKeyValueStoreClient.open`.
 */
export interface AdoptionCandidate {
    key: string;
    files: Array<AdoptableFile>;
}

/**
 * One out-of-band ("bare") file fallback for `resolveValue` / `resolveExistingKey`:
 * an extension appended to the looked-up key, plus the content type to report
 * when a bare file with that extension is matched. An empty `contentType`
 * leaves the matched file's synthesized `application/octet-stream` in place.
 *
 * The core does no MIME inference of its own — the caller declares this
 * extension→content-type policy (e.g. `.json` → `application/json`).
 *
 * @deprecated Declare the file as an `AdoptionCandidate` on `open` instead.
 */
export interface BareFallback {
    extension: string;
    contentType: string;
}

/**
 * A page of dataset items returned by `getData`. Mirrors the core's
 * `DatasetItemsListPage` so napi emits an honest TS interface instead of a
 * hand-written one. The `items` are arbitrary user JSON, so they cross the
 * FFI as `serde_json::Value` and are typed `Record<string, unknown>[]`.
 */
export interface DatasetItemsListPage {
    count: number;
    offset: number;
    limit: number;
    total: number;
    desc: boolean;
    items: Record<string, unknown>[];
}

export interface DatasetMetadata {
    id: string;
    name?: string;
    accessedAt: Date;
    createdAt: Date;
    modifiedAt: Date;
    itemCount: number;
}

/**
 * A single self-describing page of keys returned by `listKeys`. Mirrors the
 * core's `KvsListKeysResult` and crawlee's `KeyValueStoreListKeysResult`
 * contract (upstream crawlee PR #3800): the page's `items` plus the metadata a
 * caller needs to paginate.
 *
 * `exclusiveStartKey` and `nextExclusiveStartKey` are optional (omitting
 * `use_nullable` keeps them as `foo?: string` rather than `foo: string | null`,
 * matching how `UnprocessedRequest.method` is handled): `exclusiveStartKey` is
 * absent when the caller listed from the beginning, and `nextExclusiveStartKey`
 * is set iff `isTruncated` is `true`.
 */
export interface KeyValueStoreListKeysResult {
    items: Array<KeyValueStoreRecordMetadata>;
    /**
     * Number of items in this page (`items.length`). Typed `f64` (same
     * rationale as `KeyValueStoreRecordMetadata::size`) so it crosses the FFI
     * as a JS `number`.
     */
    count: number;
    /** The per-page limit the caller requested for this page. */
    limit: number;
    exclusiveStartKey?: string;
    isTruncated: boolean;
    nextExclusiveStartKey?: string;
}

export interface KeyValueStoreMetadata {
    id: string;
    name?: string;
    accessedAt: Date;
    createdAt: Date;
    modifiedAt: Date;
}

/**
 * A KVS record returned by `getValue`: the raw value bytes as a `Buffer`
 * alongside the key, content type, and size. The `value: Buffer` crosses the
 * FFI directly instead of as a per-byte JSON number array.
 */
export interface KeyValueStoreRecord {
    key: string;
    contentType: string;
    /**
     * Byte length of the value. Typed `f64` so it crosses the FFI as a JS
     * `number` (matching crawlee's `KeyValueStoreItemData.size: number`)
     * without the 4 GiB ceiling a `u32` would impose; a `usize` length is
     * exact in an `f64` up to 2^53 bytes (8 PiB), well beyond any KVS record.
     */
    size: number;
    value: Buffer;
}

/**
 * Metadata for a single KVS record, as listed by `listKeys`. Mirrors the
 * core's `KeyValueStoreRecordMetadata` with `size` finalized to a non-optional
 * value.
 */
export interface KeyValueStoreRecordMetadata {
    key: string;
    contentType: string;
    /**
     * Byte length of the value. Typed `f64` (same rationale as
     * `KeyValueStoreRecord::size`): exact up to 2^53 bytes, no 4 GiB ceiling.
     */
    size: number;
}

/**
 * One out-of-band ("bare") file to surface from `listKeys`: `name` is the
 * file's on-disk key (e.g. `"INPUT.json"`) and `contentType` is what to report
 * for it (an empty string reports the synthesized `application/octet-stream`).
 * A bare file whose on-disk name already has a tracked record is not listed
 * twice.
 *
 * Round-trip caveat: the file is listed under the literal `name`, but that key
 * does NOT round-trip through `getValue` / `recordExists` (which ignore
 * sidecar-less files and return `null` / `false`). Read a listed bare key back
 * via `resolveValue` / `resolveExistingKey` instead.
 *
 * As with `resolveValue`, the core does no MIME inference — the caller declares
 * this name→content-type policy.
 *
 * @deprecated Declare the file as an `AdoptionCandidate` on `open` instead,
 * which lists it as an ordinary record.
 */
export interface ListBareFallback {
    name: string;
    contentType: string;
}

/**
 * The content-type sentinel for null KVS values (stored on disk as an empty
 * file). Re-exported from the core crate so consumers reference the shared
 * constant instead of hardcoding the `application/x-none` literal.
 */
export const NONE_CONTENT_TYPE: string;

/**
 * Result of processing one request in `addBatchOfRequests`. Mirrors the core's
 * `ProcessedRequest`.
 */
export interface ProcessedRequest {
    requestId: string;
    uniqueKey: string;
    wasAlreadyPresent: boolean;
    wasAlreadyHandled: boolean;
}

export interface RequestQueueMetadata {
    id: string;
    name?: string;
    accessedAt: Date;
    createdAt: Date;
    modifiedAt: Date;
    handledRequestCount: number;
    pendingRequestCount: number;
    totalRequestCount: number;
}

/**
 * A request that could not be processed in `addBatchOfRequests`. Mirrors the
 * core's `UnprocessedRequest`. `method` is optional; omitting `use_nullable`
 * keeps it as `method?: string` rather than `method: string | null`.
 */
export interface UnprocessedRequest {
    uniqueKey: string;
    url: string;
    method?: string;
}
