// Metadata interfaces (DatasetMetadata, KeyValueStoreMetadata,
// RequestQueueMetadata) and the KeyValueStoreRecord interface are
// auto-generated by napi-rs from `#[napi(object)]` structs in src/models.rs —
// the metadata datetime fields come through as native `Date` (thanks to napi's
// `chrono_date` feature) and the record's `value` comes through as a `Buffer`.

export interface DatasetItemsListPage {
    count: number;
    offset: number;
    limit: number;
    total: number;
    desc: boolean;
    items: Record<string, unknown>[];
}

export interface KeyValueStoreStreamRecord {
    key: string;
    contentType: string;
    size: number;
    stream: ReadableStream<Uint8Array>;
}

export interface KeyValueStoreRecordMetadata {
    key: string;
    contentType: string;
    size: number;
}

export interface ProcessedRequest {
    requestId: string;
    uniqueKey: string;
    wasAlreadyPresent: boolean;
    wasAlreadyHandled: boolean;
}

export interface UnprocessedRequest {
    uniqueKey: string;
    url: string;
    method?: string;
}

export interface AddRequestsResponse {
    processedRequests: ProcessedRequest[];
    unprocessedRequests: UnprocessedRequest[];
}

// The following `interface` declarations merge with the napi-generated `declare class`es
// further down in this file, adding the JS-side wrappers defined in `lib.js` directly onto
// the class signatures.

export interface DatasetItemIterator {
    [Symbol.asyncIterator](): AsyncIterator<Record<string, unknown>>;
}

export interface KvsKeyIterator {
    [Symbol.asyncIterator](): AsyncIterator<KeyValueStoreRecordMetadata>;
}

export interface FileSystemKeyValueStoreClient {
    /**
     * Get a value as a ReadableStream of bytes. Returns null if the key doesn't exist.
     *
     * When `requireRecordMetadata` is `false`, a value file without a metadata
     * sidecar is also streamable (used to read out-of-band files such as a
     * CLI-written `INPUT.json`). Defaults to `true` (sidecar required).
     */
    getValueStream(
        key: string,
        requireRecordMetadata?: boolean,
    ): Promise<KeyValueStoreStreamRecord | null>;
    /** Set a value from a ReadableStream. Consumes the entire stream and writes atomically. */
    setValueStream(
        key: string,
        stream: ReadableStream<Uint8Array>,
        contentType?: string | null,
    ): Promise<void>;
}
export declare class DatasetItemIterator {
    /** Fetch the next item. Returns null when iteration is exhausted. */
    next(): Promise<Record<string, unknown> | null>;
}

export declare class FileSystemDatasetClient {
    static open(
        id?: string | undefined | null,
        name?: string | undefined | null,
        alias?: string | undefined | null,
        storageDir?: string | undefined | null,
        useTestClock?: boolean | undefined | null,
    ): Promise<FileSystemDatasetClient>;
    /**
     * Advance the client's clock by `millis` milliseconds. Only usable when
     * the client was opened with `useTestClock: true`; throws otherwise.
     */
    advanceClockForTesting(millis: number): void;
    get pathToDataset(): string;
    get pathToMetadata(): string;
    getMetadata(): Promise<DatasetMetadata>;
    dropStorage(): Promise<void>;
    purge(): Promise<void>;
    pushData(data: Record<string, unknown> | Record<string, unknown>[]): Promise<void>;
    getData(
        offset?: number | undefined | null,
        limit?: number | undefined | null,
        desc?: boolean | undefined | null,
        skipEmpty?: boolean | undefined | null,
    ): Promise<DatasetItemsListPage>;
    iterateItems(
        offset?: number | undefined | null,
        limit?: number | undefined | null,
        desc?: boolean | undefined | null,
        skipEmpty?: boolean | undefined | null,
        pageSize?: number | undefined | null,
    ): Promise<DatasetItemIterator>;
}

export declare class FileSystemKeyValueStoreClient {
    static open(
        id?: string | undefined | null,
        name?: string | undefined | null,
        alias?: string | undefined | null,
        storageDir?: string | undefined | null,
        useTestClock?: boolean | undefined | null,
    ): Promise<FileSystemKeyValueStoreClient>;
    /**
     * Advance the client's clock by `millis` milliseconds. Only usable when
     * the client was opened with `useTestClock: true`; throws otherwise.
     */
    advanceClockForTesting(millis: number): void;
    get pathToKvs(): string;
    get pathToMetadata(): string;
    getMetadata(): Promise<KeyValueStoreMetadata>;
    dropStorage(): Promise<void>;
    /**
     * Delete all records except those whose keys are listed in `keep`.
     *
     * Matching is by exact key (no extension globbing): to spare both `INPUT`
     * and `INPUT.json`, pass both. The store metadata is always kept.
     */
    purge(keep?: Array<string> | undefined | null): Promise<void>;
    /**
     * Get a record by key. Returns the raw value bytes as a Buffer.
     *
     * When `requireRecordMetadata` is `false`, a value file without a metadata
     * sidecar is also returned (with a generic `application/octet-stream`
     * content type and no type inference) — used to read out-of-band files such
     * as a CLI-written `INPUT.json`. Defaults to `true` (sidecar required).
     */
    getValue(
        key: string,
        requireRecordMetadata?: boolean | undefined | null,
    ): Promise<KeyValueStoreRecord | null>;
    /** Set a value from a Buffer. */
    setValue(key: string, value: Buffer, contentType?: string | undefined | null): Promise<void>;
    deleteValue(key: string): Promise<void>;
    iterateKeys(
        exclusiveStartKey?: string | undefined | null,
        limit?: number | undefined | null,
        pageSize?: number | undefined | null,
        prefix?: string | undefined | null,
    ): Promise<KvsKeyIterator>;
    getPublicUrl(key: string): Promise<string>;
    /**
     * Check whether a record exists for `key`.
     *
     * When `requireRecordMetadata` is `false`, a value file with no metadata
     * sidecar also counts as existing (matching the relaxed `getValue` lookup).
     * Defaults to `true` (sidecar required).
     */
    recordExists(key: string, requireRecordMetadata?: boolean | undefined | null): Promise<boolean>;
}

export declare class FileSystemRequestQueueClient {
    /**
     * Open a request queue.
     *
     * `useTestClock`: see `advanceClockForTesting` below.
     *
     * `assumeSoleOwner` (default `true`): controls how locks on disk are
     * treated at open time. With `true` (the default, tuned for the common
     * single-process crawl), the caller asserts nothing else is using this
     * queue and any in-progress locks are reclaimed immediately, so a request
     * whose previous run died is instantly re-fetchable. Set to `false` when
     * multiple processes share the same on-disk queue concurrently: any
     * future-dated `orderNo` is then respected as a potential live peer's
     * lock, and crashed peers' locks expire naturally on the wall clock —
     * otherwise you risk two peers processing the same request.
     */
    static open(
        id?: string | undefined | null,
        name?: string | undefined | null,
        alias?: string | undefined | null,
        storageDir?: string | undefined | null,
        useTestClock?: boolean | undefined | null,
        assumeSoleOwner?: boolean | undefined | null,
    ): Promise<FileSystemRequestQueueClient>;
    /**
     * Advance the client's clock by `millis` milliseconds. Only usable when
     * the client was opened with `useTestClock: true`; throws otherwise.
     *
     * This is the hook that lets JS tests using `vi.useFakeTimers()` exercise
     * lock-expiry behavior — fake JS timers don't reach into native code, so
     * the test must drive the Rust-side clock explicitly via this method.
     */
    advanceClockForTesting(millis: number): void;
    get pathToRq(): string;
    get pathToMetadata(): string;
    getMetadata(): Promise<RequestQueueMetadata>;
    dropStorage(): Promise<void>;
    purge(): Promise<void>;
    addBatchOfRequests(
        requests: Record<string, unknown>[],
        forefront?: boolean | undefined | null,
    ): Promise<AddRequestsResponse>;
    getRequest(uniqueKey: string): Promise<Record<string, unknown> | null>;
    fetchNextRequest(): Promise<Record<string, unknown> | null>;
    markRequestAsHandled(request: Record<string, unknown>): Promise<ProcessedRequest | null>;
    reclaimRequest(
        request: Record<string, unknown>,
        forefront?: boolean | undefined | null,
    ): Promise<ProcessedRequest | null>;
    isEmpty(): Promise<boolean>;
    isFinished(): Promise<boolean>;
    setExpectedRequestProcessingTime(secs: number): Promise<void>;
    persistState(): Promise<void>;
}

export declare class KvsKeyIterator {
    /** Fetch the next key metadata entry. Returns null when iteration is exhausted. */
    next(): Promise<KeyValueStoreRecordMetadata | null>;
}

export interface DatasetMetadata {
    id: string;
    name?: string;
    accessedAt: Date;
    createdAt: Date;
    modifiedAt: Date;
    itemCount: number;
}

export interface KeyValueStoreMetadata {
    id: string;
    name?: string;
    accessedAt: Date;
    createdAt: Date;
    modifiedAt: Date;
}

/**
 * A KVS record returned by `getValue`: the raw value bytes as a `Buffer`
 * alongside the key, content type, and size. Replaces the hand-written
 * `KeyValueStoreRecord` interface that used to live in `dts-header.d.ts` —
 * the `value: Buffer` now crosses the FFI directly instead of as a per-byte
 * JSON number array.
 */
export interface KeyValueStoreRecord {
    key: string;
    contentType: string;
    /**
     * Byte length of the value. Typed `f64` so it crosses the FFI as a JS
     * `number` (matching crawlee's `KeyValueStoreItemData.size: number`)
     * without the 4 GiB ceiling a `u32` would impose; a `usize` length is
     * exact in an `f64` up to 2^53 bytes (8 PiB), well beyond any KVS record.
     */
    size: number;
    value: Buffer;
}

/**
 * The content-type sentinel for null KVS values (stored on disk as an empty
 * file). Re-exported from the core crate so consumers reference the shared
 * constant instead of hardcoding the `application/x-none` literal.
 */
export const NONE_CONTENT_TYPE: string;

export interface RequestQueueMetadata {
    id: string;
    name?: string;
    accessedAt: Date;
    createdAt: Date;
    modifiedAt: Date;
    hadMultipleClients: boolean;
    handledRequestCount: number;
    pendingRequestCount: number;
    totalRequestCount: number;
}
