// Public types are auto-generated by napi-rs in `./index.d.ts` (from the
// `#[napi(object)]` mirror structs in `src/models.rs` and the `#[napi]` method
// signatures in `src/lib.rs`). This file declares only the JS-side wrappers
// added in `./lib.js` — the stream-based KVS methods and the
// `Symbol.asyncIterator` glue on the iterators — which have no Rust counterpart,
// then re-exports everything from `./index.js`.

export * from './index.js';

/**
 * A KVS record whose value is delivered as a Web `ReadableStream` of bytes
 * rather than buffered in memory. Returned by `getValueStream`.
 */
export interface KeyValueStoreStreamRecord {
    key: string;
    contentType: string;
    size: number;
    stream: ReadableStream<Uint8Array>;
}

// Augment the napi-generated classes in `./index.d.ts` with the wrappers
// defined in `./lib.js` (which `./index.d.ts` knows nothing about).
declare module './index.js' {
    interface FileSystemKeyValueStoreClient {
        /**
         * Get a tracked record's value as a ReadableStream of bytes. Returns null if
         * there is no tracked record (value file + metadata sidecar) for the key.
         */
        getValueStream(key: string): Promise<KeyValueStoreStreamRecord | null>;
        /** Set a value from a ReadableStream. Consumes the entire stream and writes atomically. */
        setValueStream(
            key: string,
            stream: ReadableStream<Uint8Array>,
            contentType?: string | null,
        ): Promise<void>;
    }
}
