name: CI (main)

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**" # Ignore all tags to avoid duplicate executions triggered by tag pushes.

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  code_checks:
    name: Code checks
    uses: ./.github/workflows/_check_code.yaml

  release_prepare:
    # Run this only for commits that would trigger a version bump.
    if: >-
      startsWith(github.event.head_commit.message, 'feat') ||
      startsWith(github.event.head_commit.message, 'fix') ||
      startsWith(github.event.head_commit.message, 'perf') ||
      startsWith(github.event.head_commit.message, 'refactor') ||
      startsWith(github.event.head_commit.message, 'style')
    name: Release prepare
    needs: [code_checks]
    runs-on: ubuntu-latest
    outputs:
      version_number: ${{ steps.release_metadata.outputs.version_number }}
      tag_name: ${{ steps.release_metadata.outputs.tag_name }}
      changelog: ${{ steps.release_metadata.outputs.changelog }}
    steps:
      - uses: apify/actions/git-cliff-release@v1.1.1
        id: release_metadata
        name: Prepare release metadata
        with:
          release_type: prerelease
          existing_changelog_path: CHANGELOG.md

  changelog_update:
    name: Changelog update
    needs: [release_prepare]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.APIFY_SERVICE_ACCOUNT_GITHUB_TOKEN }}

      - name: Write changelog
        uses: DamianReeves/write-file-action@master
        with:
          path: CHANGELOG.md
          contents: ${{ needs.release_prepare.outputs.changelog }}
          write-mode: overwrite

      - name: Commit changelog
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "chore(release): Update changelog [skip ci]"
